# Generated by Django 5.0.2 on 2024-03-25 09:50

import django.db.models.deletion
import django_ckeditor_5.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, verbose_name='Название')),
                ('header', models.CharField(max_length=70, verbose_name='Заголовок')),
                ('header_article', models.CharField(max_length=70, verbose_name='Заголовок статьи')),
                ('article', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст статьи')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'О сайте',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('image', models.ImageField(blank=True, upload_to='category_img/', verbose_name='Фото')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=350, verbose_name='Заголовок')),
                ('short', models.CharField(blank=True, max_length=150, verbose_name='Короткий заголовок')),
                ('article', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Статья')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('image', models.ImageField(blank=True, upload_to='news_img/%Y/%h/%d', verbose_name='Фото')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='news_app.category', verbose_name='Категория')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='PostPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=350, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='news_img/%Y/%h/%d', verbose_name='Фото')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.post', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Фото статей',
                'verbose_name_plural': 'Фото статей',
                'ordering': ['date'],
            },
        ),
    ]
