# Generated by Django 5.0.1 on 2024-02-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, verbose_name='Название')),
                ('header', models.CharField(max_length=70, verbose_name='Заголовок')),
                ('header_article', models.CharField(max_length=70, verbose_name='Заголовок статьи')),
                ('article', models.TextField(verbose_name='Текст статьи')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'О сайте',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_img/', verbose_name='Фото'),
        ),
    ]
