# Generated by Django 5.0.1 on 2024-02-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_about_category_draft_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=350, verbose_name='Заголовок')),
                ('article', models.TextField(verbose_name='Статья')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('main_image', models.ImageField(blank=True, upload_to='news_img/%Y/%m/%d', verbose_name='Обложка')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
        ),
    ]
