# Generated by Django 5.0.1 on 2024-02-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_post_category_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
