# Generated by Django 5.0.1 on 2024-02-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='news_img/%Y/%m/%d/%h', verbose_name='Фото поста'),
        ),
    ]
