# Generated by Django 5.0.1 on 2024-02-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='news_img/%Y/%h/%d', verbose_name='Обложка'),
        ),
    ]
