# Generated by Django 5.0.1 on 2024-02-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0010_postphotos_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostPhotos',
            new_name='PostPhoto',
        ),
    ]
