# Generated by Django 5.0.1 on 2024-02-20 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0011_rename_postphotos_postphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='postphoto',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 20, 16, 13, 12, 67721, tzinfo=datetime.timezone.utc), verbose_name='Добавлено'),
            preserve_default=False,
        ),
    ]
