# Generated by Django 5.0.1 on 2024-02-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0012_postphoto_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postphoto',
            old_name='data',
            new_name='date',
        ),
    ]
