# Generated by Django 5.0.1 on 2024-02-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0013_rename_data_postphoto_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postphoto',
            options={'verbose_name': 'Фото статьи', 'verbose_name_plural': 'Фото статьи'},
        ),
        migrations.AddField(
            model_name='post',
            name='short',
            field=models.CharField(blank=True, max_length=150, verbose_name='Короткий заголовок'),
        ),
    ]
