# Generated by Django 5.0.1 on 2024-02-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0014_alter_postphoto_options_post_short'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='short',
            new_name='title',
        ),
    ]
