# Generated by Django 5.0.1 on 2024-02-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0015_rename_short_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='short',
        ),
    ]
