# Generated by Django 5.0.2 on 2024-03-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0016_rename_title_post_short'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postphoto',
            options={'ordering': ['date'], 'verbose_name': 'Фото статей', 'verbose_name_plural': 'Фото статей'},
        ),
    ]
