# Generated by Django 5.0.2 on 2024-03-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0019_alter_post_options'),
    ]

    operations = [
        migrations.RunSQL(
            ('CREATE FULLTEXT INDEX news_app_fulltext_index ON news_app_post (header, article)',),
            ('DROP INDEX news_app_fulltext_index on news_app_post',)
        )
    ]
